# Generated by Django 4.2.7 on 2023-12-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlistcoinassociative',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.coin'),
            preserve_default=False,
        ),
    ]
