# Generated by Django 4.2.7 on 2023-12-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_coinlistcoinassociative_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.coin')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.currency')),
            ],
            options={
                'ordering': ['coin', 'currency'],
            },
        ),
    ]
