# Generated by Django 4.2.7 on 2024-01-08 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_coinconverter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinlistcoinassociative',
            name='coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.coin'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
